CREATE TABLE medicos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    crm VARCHAR(255) NOT NULL UNIQUE,
    especialidade VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);